title: A solução para seus problemas
description: My Personal Stack Problems
author: Daniel Rocha
github: https://github.com/rochadaniel
about: Desenvolvedor mobile e amante da tecnologia :)
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-github
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  fb_appid: 1749788565247320

urls:
    - text: Quem sou eu
      url: /about/
    - text: Projetos
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://rochadaniel.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
