title: Blog
description: Compartilhando um pouco de experiência
author: Daniel Rocha
github: https://github.com/rochadaniel
about: Desenvolvedor mobile e amante da tecnologia :)
disqus_shortname: rochadaniel
google_analytics: UA-53685939-7

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/rochadaniel"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/danielrochadev"
    # - icon: fa-stack-exchange
    #   link: "#"

share:
  fb_appid: 1808598809355293

urls:
    - text: Categorias
      url: /category/android
    - text: Quem sou eu
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://rochadaniel.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
